#! /usr/bin/env python3
# coding: utf-8
import pandas as pd
import itertools
import os
import utils
import mysql.connector
import db_credentials


def main():
    pass

if __name__ == "__main__":
	MYDB = mysql.connector.connect(
	  host = db_credentials.host,
	  user = db_credentials.user,
	  passwd = db_credentials.passwd,
	  database = db_credentials.database)

	SQL = "SELECT * FROM processed_stock LEFT JOIN candlestick_indicator ON processed_stock.id = candlestick_indicator.id UNION SELECT * FROM processed_stock RIGHT JOIN candlestick_indicator ON processed_stock.id = candlestick_indicator.id"
	NAME_DICT={0:"index", 1:"date_of_day" , 2:"hour" , 3:"name" , 4:"volume" , 5:"numberOfTrades" , 6:"var_ema" , 7:"var_bollinger" , 8:"var_stoch" , 9:"rsi_indicator" , 10:"stoch_indicator" , 11:"RSI" , 12:"ema_indicator" , 13:"bollinger_indicator" , 14:"fft_20_close" , 15:"fft_100_close" , 16:"fft_100_open" , 17:"fft_100_low" , 18:"fft_100_high", 19:'ema_12', 20:'ema_26', 21:'upper_list', 22:'lower_list',23:'k_value',24:'D_VALue', 25:"index2", 26:"CDL2CROWS" , 27:"CDL3BLACKCROWS" , 28:"CDL3INSIDE" , 29:"CDL3LINESTRIKE" , 30:"CDL3OUTSIDE" , 31:"CDL3STARSINSOUTH" , 32:"CDL3WHITESOLDIERS" , 33:"CDLABANDONEDBABY" , 34:"CDLADVANCEBLOCK" , 35:"CDLBELTHOLD" , 36:"CDLBREAKAWAY" , 37:"CDLCLOSINGMARUBOZU" , 38:"CDLCONCEALBABYSWALL" , 39:"CDLCOUNTERATTACK" , 40:"CDLDARKCLOUDCOVER" , 41:"CDLDOJI" , 42:"CDLDOJISTAR" , 43:"CDLDRAGONFLYDOJI" , 44:"CDLENGULFING" , 45:"CDLEVENINGDOJISTAR" , 46:"CDLEVENINGSTAR" , 47:"CDLGAPSIDESIDEWHITE" , 48:"CDLGRAVESTONEDOJI" , 49:"CDLHAMMER" , 50:"CDLHANGINGMAN" , 51:"CDLHARAMI" , 52:"CDLHARAMICROSS" , 53:"CDLHIGHWAVE" , 54:"CDLHIKKAKE" , 55:"CDLHIKKAKEMOD" , 56:"CDLHOMINGPIGEON" , 57:"CDLIDENTICAL3CROWS" , 58:"CDLINNECK" , 59:"CDLINVERTEDHAMMER" , 60:"CDLKICKING" , 61:"CDLKICKINGBYLENGTH" , 62:"CDLLADDERBOTTOM" , 63:"CDLLONGLEGGEDDOJI" , 64:"CDLLONGLINE" , 65:"CDLMARUBOZU" , 66:"CDLMATCHINGLOW" , 67:"CDLMATHOLD" , 68:"CDLMORNINGDOJISTAR" , 69:"CDLMORNINGSTAR" , 70:"CDLONNECK" , 71:"CDLPIERCING" , 72:"CDLRICKSHAWMAN" , 73:"CDLRISEFALL3METHODS" , 74:"CDLSEPARATINGLINES" , 75:"CDLSHOOTINGSTAR" , 76:"CDLSHORTLINE" , 77:"CDLSPINNINGTOP" , 78:"CDLSTALLEDPATTERN" , 79:"CDLSTICKSANDWICH" , 80:"CDLTAKURI" , 81:"CDLTASUKIGAP" , 82:"CDLTHRUSTING" , 83:"CDLTRISTAR" , 84:"CDLUNIQUE3RIVER" , 85:"CDLUPSIDEGAP2CROWS" , 86:"CDLXSIDEGAP3METHODS"}
	df = utils.get_data(MYDB, SQL, NAME_DICT)

	if isinstance(df, int) == False and len(df) != 0:
		df = df.drop('index2', 1)
		SQL = "INSERT INTO unlabelled_record (date_of_day,hour,name,volume,numberOfTrades,var_ema,var_bollinger,var_stoch,rsi_indicator,stoch_indicator,RSI,ema_indicator,bollinger_indicator,CDL2CROWS,CDL3BLACKCROWS,CDL3INSIDE,CDL3LINESTRIKE,CDL3OUTSIDE,CDL3STARSINSOUTH,CDL3WHITESOLDIERS,CDLABANDONEDBABY,CDLADVANCEBLOCK,CDLBELTHOLD,CDLBREAKAWAY,CDLCLOSINGMARUBOZU,CDLCONCEALBABYSWALL,CDLCOUNTERATTACK,CDLDARKCLOUDCOVER,CDLDOJI,CDLDOJISTAR,CDLDRAGONFLYDOJI,CDLENGULFING,CDLEVENINGDOJISTAR,CDLEVENINGSTAR,CDLGAPSIDESIDEWHITE,CDLGRAVESTONEDOJI,CDLHAMMER,CDLHANGINGMAN,CDLHARAMI,CDLHARAMICROSS,CDLHIGHWAVE,CDLHIKKAKE,CDLHIKKAKEMOD,CDLHOMINGPIGEON,CDLIDENTICAL3CROWS,CDLINNECK,CDLINVERTEDHAMMER,CDLKICKING,CDLKICKINGBYLENGTH,CDLLADDERBOTTOM,CDLLONGLEGGEDDOJI,CDLLONGLINE,CDLMARUBOZU,CDLMATCHINGLOW,CDLMATHOLD,CDLMORNINGDOJISTAR,CDLMORNINGSTAR,CDLONNECK,CDLPIERCING,CDLRICKSHAWMAN,CDLRISEFALL3METHODS,CDLSEPARATINGLINES,CDLSHOOTINGSTAR,CDLSHORTLINE,CDLSPINNINGTOP,CDLSTALLEDPATTERN,CDLSTICKSANDWICH,CDLTAKURI,CDLTASUKIGAP,CDLTHRUSTING,CDLTRISTAR,CDLUNIQUE3RIVER,CDLUPSIDEGAP2CROWS,CDLXSIDEGAP3METHODS,fft_20_close,fft_100_close,fft_100_open,fft_100_low,fft_100_high,ema_12,ema_26,upper_list,lower_list,k_value,D_VALue) values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
		df = df[["date_of_day","hour","name","volume","numberOfTrades","var_ema","var_bollinger","var_stoch","rsi_indicator","stoch_indicator","RSI","ema_indicator","bollinger_indicator","CDL2CROWS","CDL3BLACKCROWS","CDL3INSIDE","CDL3LINESTRIKE","CDL3OUTSIDE","CDL3STARSINSOUTH","CDL3WHITESOLDIERS","CDLABANDONEDBABY","CDLADVANCEBLOCK","CDLBELTHOLD","CDLBREAKAWAY","CDLCLOSINGMARUBOZU","CDLCONCEALBABYSWALL","CDLCOUNTERATTACK","CDLDARKCLOUDCOVER","CDLDOJI","CDLDOJISTAR","CDLDRAGONFLYDOJI","CDLENGULFING","CDLEVENINGDOJISTAR","CDLEVENINGSTAR","CDLGAPSIDESIDEWHITE","CDLGRAVESTONEDOJI","CDLHAMMER","CDLHANGINGMAN","CDLHARAMI","CDLHARAMICROSS","CDLHIGHWAVE","CDLHIKKAKE","CDLHIKKAKEMOD","CDLHOMINGPIGEON","CDLIDENTICAL3CROWS","CDLINNECK","CDLINVERTEDHAMMER","CDLKICKING","CDLKICKINGBYLENGTH","CDLLADDERBOTTOM","CDLLONGLEGGEDDOJI","CDLLONGLINE","CDLMARUBOZU","CDLMATCHINGLOW","CDLMATHOLD","CDLMORNINGDOJISTAR","CDLMORNINGSTAR","CDLONNECK","CDLPIERCING","CDLRICKSHAWMAN","CDLRISEFALL3METHODS","CDLSEPARATINGLINES","CDLSHOOTINGSTAR","CDLSHORTLINE","CDLSPINNINGTOP","CDLSTALLEDPATTERN","CDLSTICKSANDWICH","CDLTAKURI","CDLTASUKIGAP","CDLTHRUSTING","CDLTRISTAR","CDLUNIQUE3RIVER","CDLUPSIDEGAP2CROWS","CDLXSIDEGAP3METHODS","fft_20_close","fft_100_close","fft_100_open","fft_100_low","fft_100_high","ema_12","ema_26","upper_list","lower_list","k_value","D_VALue"]]
		VAL = [tuple(x) for x in df.values]
		if len(VAL) > 0:
			utils.insert_data(MYDB,SQL,VAL)
		else:
			print('no data to insert')
	else:
		print('empty dataframe')